services:
  App\Service\ProductService:
    public: true
    arguments:
      - '@App\Repository\ProductRepository'
      - '@App\Service\PaginationService'

  App\Service\PaginationService:
    arguments:
      - '@request_stack'
      - '@App\Factory\ResultFactory'

  App\Service\LoggerService:
    arguments:
      - '@logger'

  App\Service\MailSenderService:
    arguments:
      - '@Symfony\Component\Mailer\MailerInterface'
