version: '3.3'
services:
  db:
    image: mysql:5.7
    command: mysqld --user=root
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_DATABASE: 'shop'
      MYSQL_USER: 'master'
      MYSQL_PASSWORD: 'RjP79Aaj7dfV'
      MYSQL_ROOT_PASSWORD: 'RjP79Aaj7dfV'
    ports:
      - '3310:3306'
    expose:
      - '3306'
