parameters:

services:
    _defaults:
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    App\Controller\HomeController:
        tags: ['controller.service_arguments']
        arguments:
            - '@twig'
            - '@App\Service\ProductService'
