<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKVOemMe\App_KernelLocDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKVOemMe/App_KernelLocDebugContainer.php') {
    touch(__DIR__.'/ContainerKVOemMe.legacy');

    return;
}

if (!\class_exists(App_KernelLocDebugContainer::class, false)) {
    \class_alias(\ContainerKVOemMe\App_KernelLocDebugContainer::class, App_KernelLocDebugContainer::class, false);
}

return new \ContainerKVOemMe\App_KernelLocDebugContainer([
    'container.build_hash' => 'KVOemMe',
    'container.build_id' => '0e58da17',
    'container.build_time' => 1600077121,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKVOemMe');
