<?php

namespace ContainerKVOemMe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerService extends App_KernelLocDebugContainer
{
    /**
     * Gets the public 'App\Controller\HomeController' shared service.
     *
     * @return \App\Controller\HomeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/HomeController.php';
        include_once \dirname(__DIR__, 4).'/src/Chain/ServiceChain.php';
        include_once \dirname(__DIR__, 4).'/src/Service/DocumentAbstract.php';
        include_once \dirname(__DIR__, 4).'/src/Service/DocumentInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Kopernikus/KopernikusService.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/FactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/ProductFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/tecnickcom/tcpdf/tcpdf.php';
        include_once \dirname(__DIR__, 4).'/src/Lib/Pdf.php';
        include_once \dirname(__DIR__, 4).'/src/Chain/GeneratorChain.php';
        include_once \dirname(__DIR__, 4).'/src/Generator/GeneratorAbstract.php';
        include_once \dirname(__DIR__, 4).'/src/Generator/GeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Generator/Kopernikus/KopernikusGenerator.php';
        include_once \dirname(__DIR__, 4).'/src/Provider/PdfProvider.php';
        include_once \dirname(__DIR__, 4).'/src/Service/BlockService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ExelReaderService.php';
        include_once \dirname(__DIR__, 4).'/src/Transformer/ExelDataTransformer.php';
        include_once \dirname(__DIR__, 4).'/src/Generator/Kopernikus/KopernikusHUGenerator.php';

        $a = ($container->services['twig'] ?? $container->load('getTwigService'));
        $b = new \App\Chain\ServiceChain();

        $c = new \App\Chain\GeneratorChain();

        $d = ($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)));
        $e = new \App\Provider\PdfProvider();
        $f = new \App\Service\BlockService($d);
        $g = new \App\Service\ExelReaderService(new \App\Transformer\ExelDataTransformer());

        $c->addService(new \App\Generator\Kopernikus\KopernikusGenerator($d, $e, $f, $g), 'kopernikus');
        $c->addService(new \App\Generator\Kopernikus\KopernikusHUGenerator($d, $e, $f, $g), 'kopernikus');

        $b->addService(new \App\Service\Kopernikus\KopernikusService($a, ($container->services['router'] ?? $container->getRouterService()), ($container->services['form.factory'] ?? $container->load('getForm_FactoryService')), new \App\Factory\ProductFactory(new \App\Lib\Pdf()), $c), 'kopernikus');

        return $container->services['App\\Controller\\HomeController'] = new \App\Controller\HomeController($a, $b);
    }
}
