<?php

namespace ContainerCkMCuNc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\HomeController' shared service.
     *
     * @return \App\Controller\HomeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/HomeController.php';
        include_once \dirname(__DIR__, 4).'/src/Chain/ServiceChain.php';
        include_once \dirname(__DIR__, 4).'/src/Service/DocumentAbstract.php';
        include_once \dirname(__DIR__, 4).'/src/Service/DocumentInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Kopernikus/KopernikusAktienkorbService.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/FactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/ProductFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/tecnickcom/tcpdf/tcpdf.php';
        include_once \dirname(__DIR__, 4).'/src/Lib/PdfInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Lib/Pdf.php';
        include_once \dirname(__DIR__, 4).'/src/Chain/GeneratorChain.php';
        include_once \dirname(__DIR__, 4).'/src/Generator/GeneratorAbstract.php';
        include_once \dirname(__DIR__, 4).'/src/Generator/GeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Generator/Kopernikus/Aktienkorb/KopernikusGenerator.php';
        include_once \dirname(__DIR__, 4).'/src/Generator/Kopernikus/Aktienkorb/KopernikusCZGenerator.php';
        include_once \dirname(__DIR__, 4).'/src/Provider/PdfProvider.php';
        include_once \dirname(__DIR__, 4).'/src/Service/BlockService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ExelReaderService.php';
        include_once \dirname(__DIR__, 4).'/src/Transformer/ExelDataTransformer.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/SettingsFactory.php';
        include_once \dirname(__DIR__, 4).'/src/Generator/Kopernikus/Aktienkorb/KopernikusHUGenerator.php';
        include_once \dirname(__DIR__, 4).'/src/Generator/Kopernikus/Aktienkorb/KopernikusSIGenerator.php';
        include_once \dirname(__DIR__, 4).'/src/Generator/Kopernikus/Aktienkorb/KopernikusSKGenerator.php';
        include_once \dirname(__DIR__, 4).'/src/Generator/Kopernikus/Diamonds/DiamondsGenerator.php';
        include_once \dirname(__DIR__, 4).'/src/Generator/Tcc/Ballanced/BallancedGenerator.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Kopernikus/KopernikusDiamondsService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Tcc/TccBallancedService.php';

        $a = ($container->services['twig'] ?? $container->load('getTwigService'));
        $b = new \App\Chain\ServiceChain();

        $c = ($container->services['router'] ?? $container->getRouterService());
        $d = ($container->services['form.factory'] ?? $container->load('getForm_FactoryService'));
        $e = new \App\Factory\ProductFactory(new \App\Lib\Pdf());
        $f = new \App\Chain\GeneratorChain();

        $g = ($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)));
        $h = new \App\Provider\PdfProvider();
        $i = new \App\Service\BlockService($g);
        $j = new \App\Service\ExelReaderService(new \App\Transformer\ExelDataTransformer(), new \App\Factory\SettingsFactory());

        $f->addService(new \App\Generator\Kopernikus\Aktienkorb\KopernikusCZGenerator($g, $h, $i, $j), 'kopernikus_aktienkorb', 'cz');
        $f->addService(new \App\Generator\Kopernikus\Aktienkorb\KopernikusGenerator($g, $h, $i, $j), 'kopernikus_aktienkorb', 'de');
        $f->addService(new \App\Generator\Kopernikus\Aktienkorb\KopernikusHUGenerator($g, $h, $i, $j), 'kopernikus_aktienkorb', 'hu');
        $f->addService(new \App\Generator\Kopernikus\Aktienkorb\KopernikusSIGenerator($g, $h, $i, $j), 'kopernikus_aktienkorb', 'si');
        $f->addService(new \App\Generator\Kopernikus\Aktienkorb\KopernikusSKGenerator($g, $h, $i, $j), 'kopernikus_aktienkorb', 'sk');
        $f->addService(new \App\Generator\Kopernikus\Diamonds\DiamondsGenerator($g, $h, $i, $j), 'kopernikus_diamonds', 'de');
        $f->addService(new \App\Generator\Tcc\Ballanced\BallancedGenerator($g, $h, $i, $j), 'tcc_ballanced', 'de');

        $b->addService(new \App\Service\Kopernikus\KopernikusAktienkorbService($a, $c, $d, $e, $f), 'kopernikus_aktienkorb');
        $b->addService(new \App\Service\Kopernikus\KopernikusDiamondsService($a, $c, $d, $e, $f), 'kopernikus_diamonds');
        $b->addService(new \App\Service\Tcc\TccBallancedService($a, $c, $d, $e, $f), 'tcc_ballanced');

        return $container->services['App\\Controller\\HomeController'] = new \App\Controller\HomeController($a, $b);
    }
}
