<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX0AWP9x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX0AWP9x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX0AWP9x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX0AWP9x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX0AWP9x\App_KernelDevDebugContainer([
    'container.build_hash' => 'X0AWP9x',
    'container.build_id' => '27022b0b',
    'container.build_time' => 1601846434,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX0AWP9x');
