<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTW1OQTF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTW1OQTF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTW1OQTF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTW1OQTF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTW1OQTF\App_KernelDevDebugContainer([
    'container.build_hash' => 'TW1OQTF',
    'container.build_id' => '2410c53c',
    'container.build_time' => 1601839592,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTW1OQTF');
